export const data: Record<string, string[]> = {
    Argentina: ["Buenos Aires", "Cordoba", "Rosario"],
    Bolivia: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba"],
    Brasil: ["Sao Paulo", "Rio de Janeiro", "Brasilia"],
    Chile: ["Santiago", "Valparaiso", "Concepcion"],
    Colombia: ["Bogota", "Medellin", "Cali"],
    Ecuador: ["Quito", "Guayaquil", "Cuenca"],
    Guyana: ["Georgetown", "Linden", "New Amsterdam"],
    Paraguay: ["Asuncion", "Ciudad del Este", "Encarnacion"],
    Peru: ["Lima", "Cusco", "Arequipa"],
    Surinam: ["Paramaribo", "Lelydorp", "Nieuw Nickerie"],
    Uruguay: ["Montevideo", "Salto", "Punta del Este"],
    Venezuela: ["Caracas", "Maracaibo", "Valencia"],
    Mexico: ["Cancun", "Ciudad de Mexico", "Guadalajara"],
    Albania: ["Tirana", "Durres", "Vlore"],
    Andorra: ["Andorra la Vella", "Escaldes-Engordany", "Encamp"],
    Austria: ["Viena", "Graz", "Salzburgo"],
    Bielorrusia: ["Minsk", "Gomel", "Mogilev"],
    Belgica: ["Bruselas", "Amberes", "Gante"],
    Bulgaria: ["Sofia", "Plovdiv", "Varna"],
    Croacia: ["Zagreb", "Split", "Dubrovnik"],
    Chipre: ["Nicosia", "Limassol", "Larnaca"],
    Dinamarca: ["Copenhague", "Aarhus", "Odense"],
    Estonia: ["Tallin", "Tartu", "Narva"],
    Finlandia: ["Helsinki", "Espoo", "Tampere"],
    Francia: ["Paris", "Marsella", "Lyon"],
    Alemania: ["Berlin", "Munich", "Hamburgo"],
    Grecia: ["Atenas", "Tesalonica", "Patras"],
    Hungria: ["Budapest", "Debrecen", "Szeged"],
    Islandia: ["Reikiavik", "Kopavogur", "Hafnarfjordur"],
    Irlanda: ["Dublin", "Cork", "Limerick"],
    Italia: ["Roma", "Milan", "Napoles"],
    Kosovo: ["Pristina", "Prizren", "Peja"],
    Letonia: ["Riga", "Daugavpils", "Liepaja"],
    Liechtenstein: ["Vaduz", "Schaan", "Balzers"],
    Lituania: ["Vilna", "Kaunas", "Klaipeda"],
    Luxemburgo: ["Ciudad de Luxemburgo", "Esch-sur-Alzette", "Differdange"],
    Malta: ["La Valeta", "Sliema", "Mosta"],
    Moldavia: ["Chisinau", "Balti", "Tiraspol"],
    Monaco: ["Monaco", "Monte Carlo", "La Condamine"],
    Montenegro: ["Podgorica", "Niksic", "Herceg Novi"],
    Noruega: ["Oslo", "Bergen", "Stavanger"],
    Polonia: ["Varsovia", "Cracovia", "Lodz"],
    Portugal: ["Lisboa", "Oporto", "Braga"],
    Rumania: ["Bucarest", "Cluj-Napoca", "Timisoara"],
    Rusia: ["Moscu", "San Petersburgo", "Novosibirsk"],
    Serbia: ["Belgrado", "Novi Sad", "Nis"],
    Eslovaquia: ["Bratislava", "Kosice", "Presov"],
    Eslovenia: ["Liubliana", "Maribor", "Celje"],
    Espana: ["Madrid", "Barcelona", "Valencia"],
    Suecia: ["Estocolmo", "Gotemburgo", "Malmo"],
    Suiza: ["Zurich", "Ginebra", "Basilea"],
    Ucrania: ["Kiev", "Jarkov", "Odesa"],
  };
  